#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &

$HOME/.config/polybar/launch.sh


bspc monitor HDMI1 -d I II III IV V
bspc monitor DP1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Virt-manager state=floating
bspc rule -a Thunderbird state=floating
bspc rule -a firefox state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
